extends Node

#var WEBSOCKET_HEADER = "ws://165.22.120.163:5080"
var WEBSOCKET_HEADER = "wss://165.22.120.163:5080"
#var WEBSOCKET_HEADER = "ws://localhost:5080"
var SINGLE_PLAYER_WEBSOCKET_STRING = WEBSOCKET_HEADER + "/singlePlayerBlitzGame"
var VERSUS_PLAYER_WEBSOCKET_STRING = WEBSOCKET_HEADER + "/versusBlitzGame"
var AI_SINGLE_PLAYER_WEBSOCKET_STRING = WEBSOCKET_HEADER + "/aiBlitzGame"
var VERSUS_AI_WEBSOCKET_STRING = WEBSOCKET_HEADER + "/versusAiBlitzGame"

var EDITABLE_PLAYER_WEBSOCKET_STRING = VERSUS_PLAYER_WEBSOCKET_STRING

func _ready():
    pass
